// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://synmokxkbiofxkcfolad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5bm1va3hrYmlvZnhrY2ZvbGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNzI0ODIsImV4cCI6MjA3Mjk0ODQ4Mn0.fb9m4IglOdc9gTZ9886Y4-IWjVY6Gt8a69WrgZDa4GY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});